import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import Navbar from "./components/nav/Navbar";
import Footer from "@/components/Footer";

const roboto_slab = Roboto_Slab({ subsets: ["latin"] });

export const metadata = {
  title: "Kamil Krukowski - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body className={`${roboto_slab.className} w-full flex flex-col items-center overflow-x-hidden`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
